inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - app/policies/**/*.rb

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*.rb
