default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= Utils.env_or_credential "rubytrends_database_host", "127.0.0.1" %>
  port: <%= Utils.env_or_credential "rubytrends_database_port", "3306" %>

development:
  <<: *default
  database: rubytrends_development

test:
  <<: *default
  database: rubytrends_test

production:
  <<: *default
  database: rubytrends_production
  username: rubytrends
  password: <%= Utils.env_or_credential "rubytrends_database_password", ("" unless Rails.env.production?) %>
