version: "3.8"
services:
  db:
    container_name: rubytrends_test_db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1
  app:
    container_name: rubytrends_test
    image: rubytrends_test
    build:
      context: ../../..
      dockerfile: ./config/docker/rubytrends_test/Dockerfile
    environment:
      RAILS_ENV: test
      RUBYTRENDS_DATABASE_HOST: db
    depends_on:
      db:
        condition: service_healthy
    # Fix Selenium::WebDriver::Error::InvalidSessionIdError: invalid session id.
    # Default memory limit is 64MB, which is not enough for Chrome.
    shm_size: 256m
